# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  test:

services:

  genh-web-app:
    container_name: genh-web-app
    image: senofiinc/trial-web-bostongh
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_test
      - CONS_FABRIC_MSP_ID=genh
      - CONS_FABRIC_MSP_DOMAIN=genh.example.com
      - CONS_FABRIC_FOLDER=/var/hyperledger/
      - adminUser=user
      - adminPassword=pass
      - contractId=cctest
      - channel=trial
    volumes:
        - /var/run/:/host/var/run/
        - ../organizations/peerOrganizations/genh.example.com/tlsca/tlsca.genh.example.com-cert.pem:/var/hyperledger/pki/genh/tlsca/cert.pem
        - ../organizations/peerOrganizations/genh.example.com/users/Admin@genh.example.com/msp/signcerts/cert.pem:/var/hyperledger/pki/genh/admin/signcerts/cert.pem
        - ../organizations/peerOrganizations/genh.example.com/users/Admin@genh.example.com/msp/keystore/49882b96f93527a40f66791ad258d6cd81081a8a52cb859f20bf565c3f4879ec_sk:/var/hyperledger/pki/genh/admin/keystore/key.key
        - ../organizations/peerOrganizations/genh.example.com/connection-genh.json:/var/hyperledger/network/genh/connection.json
    ports:
      - 8088:8088
    networks:
      - test